### PR TITLE
Fix things

### LINKED ISSUE #4702: Cannot type scene background color
Typing a color background does display the appropriate color in the color picker icon, but closing the dialog doesn't register the color change. The color picker needs to be used.
image
image
image
I tried hitting Return, clicking elsewhere in the same dialog, I cannot get it to register that new color if I don't open the color picker.

GDevelop v153

### LINKED ISSUE #4703: Prevent the selection of an object in the canvas isn't correctly indicate in the instance editor.
## Describe the bug
I had trouble to find why an instance was not selectable on my scene.
I didn't see the locked or forbiden sign in the instance panel, but they should be visible, because I had check the checkbox in the propertie panel.
I had to retreive which instance was locked by the name. There was no other solution.

## To Reproduce
0. Normal state of an instance in the instance panel 
image
1. Click `Lock position/angle in the editor` the instance panel is updated with 
image
2. Click `Prevent selection in the canvas` the instance panel is updated with 
image

3. Uncheck `Lock position/angle in the editor`, the instance go back to the normal icon step 0, but it shouldn't.
4. It should be the forbidden sign from the step 2.
image

## Suggestion

- [ ] Change the icon on the instance to image when the two checkboxes are checked:
- `Lock position/angle in the editor`  & `Prevent selection in the canvas`

- [ ] Fix the inconsistency between the two checkboxes.
Both are related to the instance on the scene editor, but on the first we talk about "the editor" and in the second about "the canvas", for explaining the same place.
It should be the same wording for the both checkboxes.
`Lock position/angle in the editor`  & `Prevent selection in the editor`

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #4702 
Fixes #4703

### CODE REVIEW

File: newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js [hunk 1]
```diff
@@ -89,12 +89,16 @@ export default class InstancePropertiesEditor extends React.Component<Props> {
...
+        instance.setLocked(newValue);
+        if (!newValue) {
+          instance.setSealed(newValue);
+        }
+      },
     },
     {
       name: 'Prevent instance selection',
-      getLabel: () => this.props.i18n._(t`Prevent selection in the canvas`),
+      getLabel: () => this.props.i18n._(t`Prevent selection in the editor`),
```
Comment (4ian) [inline newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js:101]: Yes!

**Review by 4ian — APPROVED** [review]
