### PR TITLE
Better error sending

### LINKED ISSUE #5659: Crashes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As soon as I launch the app it crashes after loading

Probably a user error, but what do I need to do?

### Steps to reproduce

Launch the app

### GDevelop platform

Desktop

### GDevelop version

latest

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Also: attempt to fix #5659 and #5776 and any other issue related to GDevelop editor crashing at the opening.

### CODE REVIEW

File: newIDE/app/src/UI/ErrorBoundary.js [hunk 1]
```diff
@@ -41,6 +41,9 @@ const errorHandler = (
     `error-boundary_${scope}`,
     {
       error,
+      errorMessage: error.message || '',
+      errorStack: error.stack || '',
+      errorName: error.name || '',
       componentStack,
```
Comment (4ian) [inline newIDE/app/src/UI/ErrorBoundary.js:47]: Also add:
getIDEVersion()
getIDEVersionWithHash()
getPlatformName
getSystemVersion
getUserAgent

File: newIDE/app/src/Utils/GDevelopServices/Asset.js [hunk 2]
```diff
@@ -176,39 +176,43 @@ export const isCompatibleWithAsset = (
...
+      .get(filtersUrl)
+      .then(response => response.data)
+      .catch(e => e),
+    client
+      .get(assetPacksUrl)
+      .then(response => response.data)
+      .catch(e => e),
+  ]);
+
+  if (responsesData.some(data => !data || data instanceof Error)) {
```
Comment (4ian) [inline newIDE/app/src/Utils/GDevelopServices/Asset.js:207]: Weird that it's necessary but ok..

**Review by 4ian — APPROVED** [review]
