### PR TITLE
Fix saving instance number value when equal to 0

### LINKED ISSUE #6932: Object properties cannot be set to 0
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

after

after

### GDevelop platform

Desktop, Web

### GDevelop version

5.4.210-e9b4de2ca9fc5e520ec99d0a9084becd5e0226a9, 

### Platform info

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #6932 

Storybook : https://gdevelop-storybook.s3.amazonaws.com/fix-expression-field-0/latest/index.html?path=/story/ui-building-blocks-compactsemicontrollednumberfield--default

### CODE REVIEW

File: newIDE/app/src/UI/CompactSemiControlledNumberField/index.js [hunk 1]
```diff
@@ -114,6 +114,24 @@ const CompactSemiControlledNumberField = ({
...
+          }
+        }}
+        onWheel={event => {
+          if (event.deltaY < 0) {
+            event.preventDefault();
+            onChangeValue((value + 1).toString(), 'keyInput');
+          }
+          if (event.deltaY > 0) {
+            event.preventDefault();
+            onChangeValue((value - 1).toString(), 'keyInput');
```
Comment (AlexandreSi) [inline newIDE/app/src/UI/CompactSemiControlledNumberField/index.js:133]: Should it be a new control? Like wheel?

**Review by 4ian — APPROVED** [review]
