### PR TITLE
Select parameter content when editing it form the event sheet

### LINKED ISSUE #1559: Text cursor not at the end of the value in case of num input
# Describe the bug
When a num type input is selected to change, the default cursor goes to the starting of the variable but I think it should be consistent with other type of data for example strings, where it goes to the end by default. 

# How to Reproduce
1. Open any project
2. Try to change a num value
3. See error as given below

String type input
image

Num type input
image

### LINKED ISSUE #2111: Text cursor position in the events sheet
When clicking on a field to edit it, the position of the text cursor is not consistent in all fields:
- Value/Text: left of the text. (with some exceptions, like tween easings)
image

- Name (object, variable, etc): right of the text. 
image

Names (and easings) are available through dropdown menus, so it might be related to that? Either way, I think it should be consistent.
Ideally, I would like the content of fields to be always highlighted when I click on the field. That way, whatever I want to do, I only need one keypress: left to go to the beginning, right to go to the end, backspace to erase (and access the dropdowns), or simply write the new name/text/value.

GD5b101

### PR DESCRIPTION
**Pull request by AlexandreSi**
Closes #1559
Closes #2111

Used @PascalLadalle suggestion: Select all content to quickly go to either the beginning or the end of the input.

demo_select_all_parameter

### CODE REVIEW

File: newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js [hunk 1]
```diff
@@ -179,9 +179,18 @@ export default class ExpressionField extends React.Component<Props, State> {
     }
   }
 
-  focus = () => {
+  focus = (selectAll: boolean = false) => {
     if (this._field) {
       this._field.focus();
+      if (selectAll) {
+        this._inputElement = this._field ? this._field.getInputNode() : null;
```
Comment (4ian) [inline newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js:186]: Is this line necessary?

File: newIDE/app/src/EventsSheet/InlineParameterEditor.js [hunk 2]
```diff
@@ -100,7 +100,7 @@ export default class InlineParameterEditor extends React.Component<
       () => {
         // Give a bit of time for the popover to mount itself
         setTimeout(() => {
-          if (this._field && this._field.focus) this._field.focus();
+          if (this._field && this._field.focus) this._field.focus(true);
```
Comment (4ian) [inline newIDE/app/src/EventsSheet/InlineParameterEditor.js:103]: ubernitpicking: 
```suggestion
          if (this._field && this._field.focus) this._field.focus(/*selectAll=*/true);
```

**Review by 4ian — APPROVED** [review]

File: newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js (hunk 1 above)
Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js]: You're right, useless!
