### PR TITLE
Fix: Convert confirm, alert calls to platform-dependent calls

### LINKED ISSUE #1646: Input fields grey out - not allowing selection or editing
There is an intermittent bug, where renaming or entering data in input fields seems to randomly break, not allowing the current entry to be selected, deleted or edited. When it happens, all input fields are affected. example: it breaks with renaming sprites, and then I cannot rename scenes, layers, etc.

It works sometimes, but other times seems to break for no reason, and then will start again randomly.

I can consistently get it to break importing images to sprites from outside the project folder and importing them in. When it does happen, alt tabbing out of the program and back in resolves the issue for a short time.

I am using windows 10 and GDevelop beta 90

### PR DESCRIPTION
**Pull request by NilayMajorwar**
Resolves #1646.
- Added `showConfirmDialog` to Window.js that uses browser's `confirm` API on web-app and `dialog.showMessageBoxSync` on Electron app. 
- Converted all `confirm` calls in the codebase to use this function, removing the now-unnecessary ESLint ignore-lines.
- Also converted an `alert` call in `path-editor.js` to use `dialog.showMessageBoxSync` instead.

Built and tested on Windows - the issue seems to be fixed.

### CODE REVIEW

File: newIDE/app/src/BehaviorsEditor/index.js [hunk 1]
```diff
@@ -76,8 +76,7 @@ export default class BehaviorsEditor extends Component {
       },
       () => {
         if (this._hasBehaviorWithType(type)) {
-          //eslint-disable-next-line
-          const answer = confirm(
+          const answer = Window.showConfirmDialog(
```
Comment (4ian) [inline newIDE/app/src/BehaviorsEditor/index.js:79]: Seems like the Window import is missing?

File: newIDE/app/src/ObjectEditor/Editors/SpriteEditor/CollisionMasksEditor/index.js [hunk 2]
```diff
@@ -129,8 +129,7 @@ export default class CollisionMasksEditor extends Component {
 
   _setSameCollisionMasksForAllAnimations = enable => {
     if (enable) {
-      // eslint-disable-next-line
-      const answer = confirm(
+      const answer = Window.showConfirmDialog(
```
Comment (4ian) [inline newIDE/app/src/ObjectEditor/Editors/SpriteEditor/CollisionMasksEditor/index.js:132]: Window import

File: newIDE/app/src/ObjectEditor/Editors/SpriteEditor/PointsEditor/PointsList.js [hunk 3]
```diff
@@ -95,8 +95,7 @@ class PointsListBody extends Component {
             });
           }}
           onRemove={() => {
-            //eslint-disable-next-line
-            const answer = confirm(
+            const answer = Window.showConfirmDialog(
```
Comment (4ian) [inline newIDE/app/src/ObjectEditor/Editors/SpriteEditor/PointsEditor/PointsList.js:98]: Window import

File: newIDE/app/src/ObjectEditor/Editors/SpriteEditor/PointsEditor/index.js [hunk 4]
```diff
@@ -105,8 +105,7 @@ export default class PointsEditor extends Component {
 
   _setSamePointsForAllAnimations = enable => {
     if (enable) {
-      // eslint-disable-next-line
-      const answer = confirm(
+      const answer = Window.showConfirmDialog(
```
Comment (4ian) [inline newIDE/app/src/ObjectEditor/Editors/SpriteEditor/PointsEditor/index.js:108]: Window import

**Comment by 4ian** [comment]
Looks mostly good! Unfortunately seems like some import Window are missing... and Window is a global so Flow did not catch this :'( 
Double check the file I mentioned and do a check on all the other files - then we should be good to go!

Thanks for taking the time to do this fix :)

**Comment by NilayMajorwar** [comment]
Really sorry for the missing imports :sweat_smile:. I've fixed the files you mentioned and double-checked all the other files for any other missing imports - I think it's good now.

**Comment by 4ian** [comment]
Looks good! 👍

**Comment by 4ian** [comment]
There was two wrong imports, I fixed them => always be sure to test your changes ;)
