### PR TITLE
Made New Scene naming convention consistent

### LINKED ISSUE #1507: Naming inconsistency in newly created scenes
## Describe the bug
The naming when new scenes are created is not consistent with the previous one.

Screenshot from 2020-03-08 15-02-10

## To Reproduce
1. Go to Project
2. Click on Add a New Scene

### PR DESCRIPTION
**Pull request by Dilshaad21**
Fixes #1507  Earlier it had a default new scene `New scene` and on successive new scene creations it created new scenes named as `NewScene` which should be `New scene2`, `New scene3` and so on.

**Before changes**
Screenshot from 2020-03-08 15-02-10 (1)

**After changes**
Screenshot from 2020-03-08 15-57-37

### CODE REVIEW

**Comment by Dilshaad21** [comment]
@4ian please review

File: newIDE/app/src/ProjectManager/index.js [hunk 1]
```diff
@@ -700,6 +700,11 @@ export default class ProjectManager extends React.Component<Props, State> {
             autoGenerateNestedIndicator={!forceOpen}
             renderNestedItems={() =>
               filterProjectItemsList(enumerateLayouts(project), searchText)
+                .sort((layout1: gdLayout,layout2: gdLayout) => {
```
Comment (4ian) [inline newIDE/app/src/ProjectManager/index.js]: Unfortunately it's important to show the order to the user because the order is important (first scene is the one launched at the beginning of the game). Can we avoid doing this for now?

Also later we may want to add tags of folders to organize scenes :)

Comment (Dilshaad21) [reply newIDE/app/src/ProjectManager/index.js]: @4ian changes have been done

**Comment by 4ian** [comment]
Merged, thanks! 👍
