### PR TITLE
Encode URL before downloading locally

### LINKED ISSUE #5597: Web link NOT working
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I am trying to generate a web link for my game but get the following error. 

**_Error while downloading the game resources. Check your internet connection and that all resources of the game are valid in the Resources editor.

Error invoking remote method 'local-file-download': TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters_**

this week I added a few .mp3 files.   Some files had spaces so I renamed the file in the folder and re-uploaded the file but still the error persisted.  I took out all the new .mp3 files and reinserted them but the error still persisted.   I downloaded the project to my local drive and tried to create a link and then the link WORKED...  so I am not sure what is going on.  I have quit gdev, restarted my computer,  changed the files but nothing worked unitl it was on my local drive.  Any ideas?

### Steps to reproduce

I am trying to generate a web link for my game but get the following error. 

**_Error while downloading the game resources. Check your internet connection and that all resources of the game are valid in the Resources editor.

Error invoking remote method 'local-file-download': TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters_**

this week I added a few .mp3 files.   Some files had spaces so I renamed the file in the folder and re-uploaded the file but still the error persisted.  I took out all the new .mp3 files and reinserted them but the error still persisted.   I downloaded the project to my local drive and tried to create a link and then the link WORKED...  so I am not sure what is going on.  I have quit gdev, restarted my computer,  changed the files but nothing worked unitl it was on my local drive.  Any ideas?

### GDevelop platform

Desktop

### GDevelop version

 5.2.169

### Platform info

<details>

mac os 13.5 (22G74)

### Additional context

I was working last week, all I did new was add about 10 .mp3 files.  I have used .mp3 files in the project and it worked fine.

### PR DESCRIPTION
**Pull request by ClementPasteau**
Attempt to fix #5597 

This fixes both starting a preview and donwloading the project with "Save as" when a resource has a non-handle character, like "👋"
I'm not sure this is done in the right place.
This could be moved inside the electron-app "local-file-download" method.
Or this logic could be done only for cloud projects by detecting the url type

### CODE REVIEW

File: newIDE/app/src/Utils/LocalFileDownloader.js [hunk 1]
```diff
@@ -16,6 +16,21 @@ export type ItemResult<Item> = {|
   error?: Error,
 |};
 
+export const sanitizeUrlWithEncodedPath = (url: string) => {
+  // Split the URL into protocol and the rest of the URL
```
Comment (4ian) [inline newIDE/app/src/Utils/LocalFileDownloader.js:20]: Out of caution, I would check that if `://` is not found (`=== -1`), then you return the url as is (because it's probably not a URL, so better don't change it)

File: newIDE/app/src/Utils/LocalFileDownloader.spec.js [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+        )
+      ).toBe(
+        'https://project-resources.gdevelop.io/1234-56a1-4cf9-8e84-123456789/resources/123456789-test%C3%A9%20%F0%9F%91%8B.jpg'
+      );
+      expect(
+        sanitizeUrlWithEncodedPath(
+          'https://project-resources.gdevelop.io/1234-56a1-4cf9-8e84-123456789/resources/123456789-testé 👋.jpg?token=abc'
+        )
+      ).toBe(
+        'https://project-resources.gdevelop.io/1234-56a1-4cf9-8e84-123456789/resources/123456789-test%C3%A9%20%F0%9F%91%8B.jpg%3Ftoken%3Dabc'
```
Comment (4ian) [inline newIDE/app/src/Utils/LocalFileDownloader.spec.js:41]: Out of caution, can you add a check for this: 
image

https://en.wikipedia.org/wiki/URL

**Comment by ClementPasteau** [comment]
I've changed the logic to use the URL API, it's actually been used in multiple part of the codebase and it does exactly what we want.
image

**Review by 4ian — APPROVED** [review]
Way better!
