### PR TITLE
Fix particle emitter rotation speed

### LINKED ISSUE #4410: Particle emitters using an image rotate ~1000x too slow
## Describe the bug

Particle emitters using images rotate ~1000x too slow

## Video 

https://user-images.githubusercontent.com/8879811/196589866-8a148146-0f50-4700-b6f7-0e2875b13afe.mp4

## Project 

[HowToMakeFallingLeaves_2.zip](https://github.com/4ian/GDevelop/files/9816537/HowToMakeFallingLeaves_2.zip)

## To Reproduce

1. Create particle emitter
2. Set the type to "image" and pick an image
3. Change max rotation speed to something high
4. Preview the game and notice particles rotating ~1000x too slow

## Other details
* Windows 11
* GDevelop 5.1.147

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #4410

### CODE REVIEW

File: Extensions/ParticleSystem/ExtensionSubDeclaration3.cpp [hunk 1]
```diff
@@ -350,17 +357,4 @@ void ExtensionSubDeclaration3(gd::ObjectMetadata& obj) {
                     _("Setup"),
                     "CppPlatform/Extensions/particleSystemicon16.png")
       .AddParameter("object", _("Object"), "ParticleEmitter", false);
-  obj.AddExpression("ParticleAngle1",
```
Comment (ClementPasteau) [inline Extensions/ParticleSystem/ExtensionSubDeclaration3.cpp:353]: if we remove them, is this gonna break games which are using them?

File: Extensions/ParticleSystem/particleemitterobject.ts [hunk 2]
```diff
@@ -49,6 +61,9 @@ namespace gdjs {
    * Displays particles.
    */
   export class ParticleEmitterObject extends gdjs.RuntimeObject {
+    /**
+     * @deprecated Data not used
```
Comment (ClementPasteau) [inline Extensions/ParticleSystem/particleemitterobject.ts:65]: is this only for angleA? angleB? I'd add this in the comment to be clear

File: Extensions/ParticleSystem/particleemitterobject.ts [hunk 3]
```diff
@@ -6,8 +6,14 @@
 
 namespace gdjs {
   export type ParticleEmitterObjectDataType = {
+    /**
+     * @deprecated Data not used
```
Comment (ClementPasteau) [inline Extensions/ParticleSystem/particleemitterobject.ts:10]: is this only for emitterAngleA? I'd add this in the comment to be clear

File: Extensions/ParticleSystem/particleemitterobject.ts [hunk 4]
```diff
@@ -388,10 +409,16 @@ namespace gdjs {
...
 
+    /**
+     * @deprecated Data not used
+     */
     getEmitterAngleA(): float {
       return this.angleA;
     }
 
+    /**
+     * @deprecated Data not used
```
Comment (ClementPasteau) [inline Extensions/ParticleSystem/particleemitterobject.ts:420]: function instead of data?

File: Extensions/ParticleSystem/particleemitterobject.ts [hunk 5]
```diff
@@ -388,10 +409,16 @@ namespace gdjs {
       }
     }
 
+    /**
+     * @deprecated Data not used
```
Comment (ClementPasteau) [inline Extensions/ParticleSystem/particleemitterobject.ts:413]: function?

File: Extensions/ParticleSystem/ExtensionSubDeclaration3.cpp (hunk 1 above)
Comment (AlexandreSi) [reply Extensions/ParticleSystem/ExtensionSubDeclaration3.cpp:353]: There is no function set for them so they were never available

**Comment by 4ian** [comment]
Lgtm once comments are addressed!

**Review by 4ian — APPROVED** [review]
