### PR TITLE
Fix scroll properties list

### LINKED ISSUE #6860: Cant scroll certain pages on mobile
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Have observed some pages do not scroll on the  iOS mobile app which limits their functionality. So far seems to affect custom object properties and function parameters, which effectively limits the number of properties or parameters which can be created/updated.

See also [my forum post](https://forum.gdevelop.io/t/can-t-scroll-custom-object-properties/60624) and [another similar one](https://forum.gdevelop.io/t/cant-scroll-function-parameters-on-mobile-version/56237) which seems to indicate this has been broken since at least April. Hopefully this is an easy fix.

### Steps to reproduce

1. Create an extension
2. Edit the extension and create a 2D object
3. Go to properties tab and add two properties (possibly more depending on phone), then try to scroll

### GDevelop platform

Mobile

### GDevelop version

5.4.207

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>iOS

*OS Version (e.g. Windows 10, macOS 10.15)*
> 17.5.1

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> iPhone 2020 SE

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Resolves #6860 

# Display improvements

| Before | After |
| --- | --- |
|  image | image |

### CODE REVIEW

File: newIDE/app/src/UI/EditorMosaic/EditorNavigator.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ const styles = {
     display: 'flex',
     flexDirection: 'column',
     flex: 1,
+    minHeight: 0,
```
Comment (AlexandreSi) [inline newIDE/app/src/UI/EditorMosaic/EditorNavigator.js:19]: This is the fix. It might fix other scrolling issues with the EditorNavigator

**Review by 4ian — APPROVED** [review]
