### PR TITLE
Fix google translate bug

### LINKED ISSUE #4234: Crash while using an editor
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:426321)
    at wu (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:439560)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:460055)
    at $i (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:384537)
    at _u (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:437418)
    at su (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:433549)
    at https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:384828
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:460055)
    at $i (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:384537)
    at Qi (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:384773)
    at Ji (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:384708)
    at nu (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:430132)
    at ba (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:401923)
    at https://editor.gdevelop.io/static/js/main.f9ac97a6.chunk.js:1:18190
    at https://editor.gdevelop.io/static/js/main.f9ac97a6.chunk.js:1:106516
    at Set.forEach (<anonymous>)
    at s (https://editor.gdevelop.io/static/js/main.f9ac97a6.chunk.js:1:106488)
    at i (https://editor.gdevelop.io/static/js/64.832c5ccd.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in span
    in button
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in It
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in Vt
    in div
    in n
    in div
    in a
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in h
    in f
    in h
    in h
    in g
    in c
    in Be
    in n
    in t
    in je
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-b9405f5e7dde404809f1f6202032b931c6c48b49
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36,

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #4234

### CODE REVIEW

File: newIDE/app/src/UI/Text.js [hunk 1]
```diff
@@ -28,6 +28,8 @@ type Props = {|
   noMargin?: boolean,
   /** Allow user to select content */
   allowSelection?: boolean,
+  /** When false, prevents browser auto translate features to translate the content (useful fore username) */
```
Comment (4ian) [inline newIDE/app/src/UI/Text.js:31]:
```suggestion
  /** When false, prevents browser auto translate features to translate the content (useful for user input, like a username) */
```

**Review by 4ian — APPROVED** [review]

File: newIDE/app/src/UI/VerticalTabButton.js [hunk 2]
```diff
@@ -69,7 +69,7 @@ const VerticalTabButton = ({
       {!hideLabel && (
         <>
           <Spacer />
-          {label}
```
Comment (ClementPasteau) [inline newIDE/app/src/UI/VerticalTabButton.js:72]: should we add a tiny comment here for future reference? something like "the span is required to avoid Google Translate crashing the app - link to issue"

**Review by ClementPasteau — APPROVED** [review]
lgtm 👍

File: newIDE/app/src/UI/VerticalTabButton.js (hunk 2 above)
Comment (4ian) [reply newIDE/app/src/UI/VerticalTabButton.js:72]: +1
