### PR TITLE
Fix renaming a layer in an external layout

### LINKED ISSUE #6136: Renaming a layer causes objects in external layouts to become invisible
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Renaming a layer causes objects in external layouts to become invisible 

### Steps to reproduce

1. Create a new layer
2. Create an external layout
3. Add objects to the external layout on the new layer
4. Rename that layer
5. Objects instances in the external layout become invisible because they are still assigned the old name of the layer

Notes:
- You can still select these instances in the editor, although the selection boxes are always at 0,0
- In the game, the objects appear at 0,0 on the base layer
- Changing the layer of the instances to the new name will make the objects reappear

image

### GDevelop platform

Desktop

### GDevelop version

5.3.186

### Platform info

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #6136

I'm wondering if there are other actions in a sceneEditor that needs to be aware that it will impact both the main scene and the external layouts associated to it.
Also, should this be done in the `WholeProjectRefactorer`?

### CODE REVIEW

File: newIDE/app/src/LayersList/index.js [hunk 1]
```diff
@@ -130,8 +130,8 @@ const LayersListBody = (props: LayersListBodyProps) => {
             }));
           } else {
             onRenameLayer(layerName, newName, doRename => {
-              if (doRename)
-                layersContainer.getLayer(layerName).setName(newName);
+              if (!doRename) return;
+              layersContainer.getLayer(layerName).setName(newName);
               gd.WholeProjectRefactorer.renameLayer(
                 project,
```
Comment (4ian) [inline newIDE/app/src/LayersList/index.js:136]: It's worth eliminating this callback "done" I guess and have just:
```
layersContainer.getLayer(layerName).setName(newName);
gd.WholeProjectRefactorer
onLayerRenamed();
```

(take the opportunity to name this "onLayerRenamed"

**Review by 4ian — APPROVED** [review]

File: newIDE/app/src/LayersList/index.js (hunk 1 above)
Comment (ClementPasteau) [reply newIDE/app/src/LayersList/index.js]: totally right, I've just done that
