### PR TITLE
Fix SetPosition (`MettreXY`) action that was missing parenthesis

### LINKED ISSUE #5456: The value modifier does not work as expected in the `Change the position of an object action`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

In the action to change the X, Y position of an object, when I put a modifier in the part where the X, Y values are entered, it does not work as expected.

### Steps to reproduce

1. Create an object
2. Move the X position to 20
3. Create an action in the event to change the X, Y Position of the object created
4. Set the Modification's sign to -(subtract) for the X position
5. Enter 10 + 5 for the X position

image

Expected result:
The X position moves by subtracting 10 + 5 from 20.

Actual result:
The X position moves by subtracting 10 from 20 and then adding 5.

### GDevelop platform

Web

### GDevelop version

5.2.166

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
> Windows 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Edge

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #5456 
Also fixes some React warning here and there

### CODE REVIEW

**Review by D8H — APPROVED** [review]
LGTM

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionParametersEditor.js [hunk 1]
```diff
@@ -206,9 +209,7 @@ const InstructionParametersEditor = React.forwardRef<
           return () => clearTimeout(timeoutId);
         }
       },
-      // We want to run this effect only when the component did mount.
```
Comment (ClementPasteau) [inline newIDE/app/src/EventsSheet/InstructionEditor/InstructionParametersEditor.js:209]: this comment is not valid anymore?

Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionParametersEditor.js:209]: I badly implemented it at the time I think
