### PR TITLE
Fix create project not retaining path

### LINKED ISSUE #1747: Folder name override while creating a project
The folder field is not propagated to the other tab, it is reset to "My projectX" every time you change tab.
image
image

GD5b93 on Windows 10 64bit

### PR DESCRIPTION
**Pull request by arthuro555**
fixes #1747 .

### CODE REVIEW

**Comment by arthuro555** [comment]
I think it is ready for review @4ian .

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js [hunk 1]
```diff
@@ -9,8 +9,24 @@ import Tutorials from './Tutorials';
 import { Column } from '../UI/Grid';
 import { type StorageProvider, type FileMetadata } from '../ProjectsStorage';
 
+class StringStore {
```
Comment (arthuro555) [inline newIDE/app/src/ProjectCreation/CreateProjectDialog.js:12]: Not sure if that is the best way, if I should have declared that in a separate file and if there wasn't an equivalent already

Comment (4ian) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:12]: You don't need this complex "string store". Just store a string in the state :)

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js [hunk 2]
```diff
@@ -9,8 +9,24 @@ import Tutorials from './Tutorials';
...
+  }
+
+  getState(): string {
+    return this.state;
+  }
+}
+
 type State = {|
   currentTab: 'starters' | 'examples' | 'tutorials',
+  outputPath: StringStore,
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/CreateProjectDialog.js:29]: outputPath: string

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js [hunk 3]
```diff
@@ -85,13 +102,15 @@ export default class CreateProjectDialog extends React.Component<Props, State> {
               onOpen={onOpen}
               onCreate={onCreate}
               onShowExamples={this._showExamples}
+              pathProvider={this.state.outputPath}
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/CreateProjectDialog.js:105]: instead of passing a complex "string store", pass something very simple:
the `outputPath`.

Then it seems that your components needs to change it.
So pass `onChangeOutputPath={(outputPath) => setState({ outputPath })}`

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js (hunk 1 above)
Comment (4ian) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:12]: Your custom string store won't notify React that something changed, because you won't call React `setState`, so the component will not re-render when there is a change,

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js (hunk 3 above)
Comment (arthuro555) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:105]: Oh, thanks! I don't really know react so I searched up on google how to share a state between parent and child and it said to use a store class. Your solution seems way better.

File: newIDE/app/src/ProjectCreation/LocalExamples.js [hunk 4]
```diff
@@ -54,11 +55,14 @@ export const showGameFileCreationError = (
 
 export default class LocalExamples extends Component<Props, State> {
   state = {
-    outputPath: findEmptyPath(
-      path && app
-        ? path.join(app.getPath('documents'), 'GDevelop projects')
-        : ''
-    ),
+    outputPath:
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/LocalExamples.js:58]: If you store the outputPath string in the parent component, you must then remove it from the state of this component. Otherwise you're duplicating the state, which comes with several risks if not done properly.

Moving the state from a component to a parent component is quite common in React. It even has a name, it's called "Lifting Up State" because you're moving from a children component to a parent component. Read this nice article about it: https://reactjs.org/docs/lifting-state-up.html

Once you get it, it's a very interesting way of thinking: all in React is about where you put the state, and what prop you give to your children :)

File: newIDE/app/src/ProjectCreation/LocalExamples.js [hunk 5]
```diff
@@ -54,11 +55,14 @@ export const showGameFileCreationError = (
...
+      this.props.pathProvider.getState() === ''
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/LocalExamples.js:59]: Then the question is "sure I moved outputPath to a prop, and stored it in the parent, but how do I initialize it??". Two possibilities:
1. Ideally, because it's the parent that is the owner of the state, it's the parent responsibility to initialize it. So you would move this code up to the parent component.
2. This being said in this case the parent is common between the electron-app and the browser app. So as an exception, we might want to have the parent keep `outputPath` empty first. Then in the children, we add a `componentDidMount` (React lifecycle function). Inside, we do `if (!this.props.outputPath) this.props.onChangeOutputPath(...)` with ... being the logic to set the output path.

File: newIDE/app/src/ProjectCreation/LocalExamples.js [hunk 6]
```diff
@@ -80,10 +84,12 @@ export default class LocalExamples extends Component<Props, State> {
     });
   }
 
-  _handleChangePath = (outputPath: string) =>
+  _handleChangePath = (outputPath: string) => {
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/LocalExamples.js:87]: After moving outputPath to the parent, you don't need _handleChangePath. Instead, you call `this.props.onChangeOutputPath`. It's the parent responsibility to store it in its state.

Why does it work? Because *any time* you change the state of a component, *then* the component is re-rendered, and all children components are-rendered with the updated props (that may or may have not changed). That's the "react way of thinking", which is ver clean once you get it:
you store things in state. You can pass props to your children, including callbacs. These callbacks can updating the state. If it's done, everything that is in the component will be re-rendered ("flowing" from parents to children). Done! :) 
See https://reactjs.org/docs/thinking-in-react.html

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js (hunk 3 above)
Comment (4ian) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:105]: People are a bit obsessed with "stores". In practice, the simplest react way to sharing things is to pass a prop with the value, and a prop with a callback to set the value.
You're not sharing actually, you're giving "just enough stuff" for your children component to do its job. No more no less (which is all the beauty/cleanliness for the components approach).

File: newIDE/app/src/ProjectCreation/LocalExamples.js (hunk 6 above)
Comment (arthuro555) [reply newIDE/app/src/ProjectCreation/LocalExamples.js:87]: Oh, that makes more sense now. Thank you very much for your time explaining it to me! (I should really have checked the react Docs before messing with it 😓 )

**Comment by arthuro555** [comment]
Ok, I did what you said, it's ready for reviewing again. I am really sorry, I should have read the docs first.

File: newIDE/app/src/ProjectCreation/CreateProjectDialog.js [hunk 7]
```diff
@@ -8,9 +8,15 @@ import { Tabs, Tab } from '../UI/Tabs';
 import Tutorials from './Tutorials';
 import { Column } from '../UI/Grid';
 import { type StorageProvider, type FileMetadata } from '../ProjectsStorage';
+import { findEmptyPath } from './LocalPathFinder';
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/CreateProjectDialog.js:11]: So this works :) The downside is that the web-app is now depending in LocalPathFinder, which is a bit sad because any LocalXXX file should not be used by the web-app (web-app = BrowserApp.js).

Comment (arthuro555) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:11]: Is that such a big deal? That file is very small, and I don't see any "react way" of solving this problem, because that would mean managing the state of the component from the children as those are electron only, but, quote from you,
> You're not sharing actually, you're giving "just enough stuff" for your children component to do its job.

So sharing the state for children for letting them handle/set it would be an anti-pattern?

Comment (4ian) [reply newIDE/app/src/ProjectCreation/CreateProjectDialog.js:11]: You're not forced to duplicate the state. Instead you can use the second solution I explained here: https://github.com/4ian/GDevelop/pull/1763#discussion_r427806624

You can the state in the parent but set it empty, and use a componentDidMount in the children to change the path (see my answer).

The third solution is to make a function that we pass in LocalApp/BrowserApp that is a function that returns the default path - but at this point we're complicating stuff too much for something so boring. 
Just put two "componentDidMount", that are setting the output path if it's empty using the prop to change it and you're done.

**Comment by arthuro555** [comment]
Ok, I did what you said except I only added componentDidMount on starters tab and not examples as it is the default mounted, and it should already have put the default path so no need for the other to put it too.

**Comment by 4ian** [comment]
Looks good! Thanks for working on this 👍
