### PR TITLE
Fix expression parameter builder

### LINKED ISSUE #3932: Expression Builder - object variables not in drop-down list
## Describe the bug

When using the expression builder, object variables do not show up on the drop-down list unless you open the object variable box first. 

## To Reproduce

use expression builder

go to object -> variables

select object - then on drop down, nothing shows up underneath.

Click on object variable dialog on right, and press close.

Drop down menu now populates.

## Other details
Windows 11 - 64bit
GDevelop 5.0.133 (was also happening on 5.0.132, not certain on earlier versions)

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #3932

### CODE REVIEW

File: newIDE/app/src/MainFrame/Preferences/PreferencesProvider.js [hunk 1]
```diff
@@ -73,8 +73,11 @@ export const getInitialPreferences = () => {
 };
 
 const getPreferences = () => {
-  const preferences =
-    loadPreferencesFromLocalStorage() || getInitialPreferences();
+  const initialPreferences = getInitialPreferences();
+  const localPreferences = loadPreferencesFromLocalStorage();
+  const preferences = localPreferences
+    ? { ...initialPreferences, ...localPreferences } // Merge initial preferences with local preferences in case a new value has been added to the preferences
```
Comment (4ian) [inline newIDE/app/src/MainFrame/Preferences/PreferencesProvider.js:79]: Is this really useful? 

It should be done already by loadPreferencesFromLocalStorage:
image

Comment (AlexandreSi) [reply newIDE/app/src/MainFrame/Preferences/PreferencesProvider.js:79]: I'll dig into it, because it seemed to me that my local preferences missed a value

Comment (AlexandreSi) [reply newIDE/app/src/MainFrame/Preferences/PreferencesProvider.js]: Indeed, that is not needed!

**Review by 4ian — APPROVED** [review]
