### PR TITLE
Fix update instructions on object change

### LINKED ISSUE #6271: Search results for actions/conditions are not updating correctly
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When one type of object is selected and any search was done for it, selecting new type of object will not change search context. Even if you delete search query (by pressing cross icon on the right for example), and select/deselect objects, search still works with "old" selection. Only re-opening popup fixes the issue.
I have tried to demonstrate problem in the video:
https://github.com/4ian/GDevelop/assets/141857198/33360813-fa92-4103-8e49-db6193c524d3

### Steps to reproduce

1. Create new condition or action.
2. Select object with unique search results.
3. Try searching for these unique properties.
4. Clear search field.
5. Select other object type.
6. Try searching with same search query, results will be for previously selected object.

### GDevelop platform

Desktop

### GDevelop version

5.3.187

### Platform info

<details>

*Windows 11*
>

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #6271

### CODE REVIEW

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js [hunk 1]
```diff
@@ -52,178 +52,167 @@ type Props<T> = {|
...
+      }),
+    [instructionsInfo]
+  );
+  const initialInstructionTypePathRef = React.useRef<?(string[])>(
+    findInTree(instructionsInfoTree, selectedType)
   );
 
-  componentDidMount() {
-    if (this._selectedItem.current && this._scrollView.current) {
-      this._scrollView.current.scrollTo(this._selectedItem.current);
```
Comment (AlexandreSi) [inline newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:79]: I removed this logic. I don't know what it was used for: How could an item be selected at the moment the component is mounted?

Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:79]: I tried to add it as an effect when the instructionsInfo prop changes so it scrolls the list so that the selected item is at the top of the list.
But I felt like it was not natural and when you switch to an object that misses the instruction (the item get unselected) and switch back to another that supports the instruction, it does not scroll to the item so it feels broken.

Comment (ClementPasteau) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:79]: Good question. I don't have the answer

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js [hunk 2]
```diff
@@ -52,178 +52,167 @@ type Props<T> = {|
...
+  searchPlaceholderIsCondition,
+  helpPagePath,
+  style,
+  onClickMore,
+  id,
+}: Props<T>) => {
+  const searchBarRef = React.useRef<?SearchBarInterface>(null);
+  const scrollViewRef = React.useRef<?ScrollViewInterface>(null);
+  const selectedItemRef = React.useRef<?ListItemRefType>(null);
+  const [searchState, setSearchState] = React.useState<SearchState<T>>({
```
Comment (ClementPasteau) [inline newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:80]: do you think it's better to use a common state rather than 2 different ones?
Is there a risk the results component re-renders only when the text change event if the results didn't?

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js [hunk 3]
```diff
@@ -52,178 +52,167 @@ type Props<T> = {|
...
-    this.searchApi = new Fuse(this.props.instructionsInfo, {
-      ...sharedFuseConfiguration,
-      keys: [
-        { name: 'displayedName', weight: 2 },
-        { name: 'fullGroupName', weight: 1 },
-      ],
-    });
-  }
-
-  focus = () => {
```
Comment (ClementPasteau) [inline newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:91]: wasn't used?

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js (hunk 2 above)
Comment (ClementPasteau) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:80]: It looks like the searchResults are not even used?

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js (hunk 3 above)
Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:91]: I couldn't find somewhere where it was used

Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:91]: (No parent component gives it a ref)

Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:91]: Maybe it was not removed at the time the focusOnMount props was added as a better replacement

File: newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js (hunk 1 above)
Comment (AlexandreSi) [reply newIDE/app/src/EventsSheet/InstructionEditor/InstructionOrExpressionSelector/index.js:79]: Yes, I just checked. It's not handled by this component anyway

**Review by ClementPasteau — APPROVED** [review]
