### PR TITLE
Use skeleton rather than loader on homepage build section

### LINKED ISSUE #4584: The homepage is jumpy due to the loading of thumbnail from game templates
## Describe the bug
The homepage is jumpy due to the loading of thumbnail from game templates
load home

## Suggestion
A [skeleton component](https://mui.com/material-ui/react-skeleton/) could help.

## Other details
* GD5

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #4584 

There's still a layout shift but it's minor. I couldn't get rid of it.

New loading view:

https://user-images.githubusercontent.com/32449369/204866394-7ebdb4d5-de42-4280-b319-4a9a2163acf2.mov

https://user-images.githubusercontent.com/32449369/204866423-4068f3c1-4991-48f3-ac0f-b2b2e839724c.mov

### CODE REVIEW

File: newIDE/app/src/MainFrame/EditorContainers/HomePage/BuildSection/index.js [hunk 1]
```diff
@@ -75,6 +76,18 @@ const getTemplatesGridSizeFromWidth = (width: WidthType) => {
   }
 };
 
+const getProjectLineHeight = (width: WidthType) => {
+  let lineHeight;
+  switch (width) {
```
Comment (ClementPasteau) [inline newIDE/app/src/MainFrame/EditorContainers/HomePage/BuildSection/index.js:81]: this switch seems quite convoluted.
You could just do `const lineHeight = width === 'small' ? 32 : 36`

**Review by ClementPasteau — APPROVED** [review]
lgtm :)
