### PR TITLE
Fix loading of 3D models not taking advantage of the cache

### LINKED ISSUE #5460: Editor hang when opening a large 3D game project
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Opening a large 3D game project will hang the editor and need to force close it.

### Steps to reproduce

[Facebook.webm](https://github.com/4ian/GDevelop/assets/35127268/ffd4d02a-0668-4983-91ee-513ffedf0c10)

### GDevelop platform

Desktop

### GDevelop version

5.2.166

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Windows

*OS Version (e.g. Windows 10, macOS 10.15)*
>Windows 10

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>-

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>-

</details>

### Additional context

Additional info: RAM and CPU usage jump so high when it hangs

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #5460

### CODE REVIEW

File: newIDE/app/src/ObjectsRendering/PixiResourcesLoader.js [hunk 1]
```diff
@@ -308,9 +310,21 @@ export default class PixiResourcesLoader {
...
 
+    const loadingPromise = PixiResourcesLoader._load3DModel(
+      project,
+      resourceName
+    );
+    loading3DModelPromises[resourceName] = loadingPromise;
+    return loadingPromise;
+  }
+
+  static _load3DModel(
```
Comment (4ian) [inline newIDE/app/src/ObjectsRendering/PixiResourcesLoader.js:324]: Consider if this can be moved out of the class (and if it's worth it) if that's a pure function

File: newIDE/app/src/ObjectsRendering/PixiResourcesLoader.js [hunk 2]
```diff
@@ -16,7 +16,9 @@ const loadedTextures = {};
 const invalidTexture = PIXI.Texture.from('res/error48.png');
 const loadedThreeTextures = {};
 const loadedThreeMaterials = {};
-const loaded3DModels = {};
+const loading3DModelPromises: {
```
Comment (4ian) [inline newIDE/app/src/ObjectsRendering/PixiResourcesLoader.js:19]: `loadedOrLoading3DModelPromises`?

**Review by 4ian — APPROVED** [review]
