### PR TITLE
Fallback to missing documents path on Windows

### LINKED ISSUE #3700: Crash while using an editor
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: Failed to get 'documents' path
Underlying stack: Error: Failed to get 'documents' path
    at electron/js2c/browser_init.js:6745:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)

    at electron/js2c/browser_init.js:6748:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)
```

## Component stack (don't write anything here)
```

    in Unknown
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.127-fff09fdbd030c1876e828d9b2c10c207629b19dc
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.22000,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.127 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #3700 & #3716 - see more info on the issue itself

### CODE REVIEW

File: newIDE/app/src/ProjectCreation/LocalPathFinder.js [hunk 1]
```diff
@@ -20,7 +20,12 @@ const findEmptyPath = (basePath: string) => {
...
 
 export const findEmptyPathInDefaultFolder = (electronApp: any): string => {
-  return findEmptyPath(
-    path.join(electronApp.getPath('documents'), 'GDevelop projects')
-  );
+  let documentsPath = '';
+  try {
+    documentsPath = electronApp.getPath('documents');
+  } catch (ex) {
+    // a user may not have the Documents folder defined on Windows.
```
Comment (4ian) [inline newIDE/app/src/ProjectCreation/LocalPathFinder.js:27]: Uber nitpicking: capital letter

**Review by 4ian — APPROVED** [review]
Sounds safer 👍
