### PR TITLE
Fix crash because of invalid texture when resetting Panel Sprite instance renderer

### LINKED ISSUE #5896: Editor crash - Manipulating a Pixi object after it being destroyed (reading 'valid')
### Describe what you were doing when the crash happened

i clicked in one of the button of my game and the screen popped up

### GDevelop version

5.3.180-4f98ffa9ab98b751f6526f4d8ac28cef0c16ed1e

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

TypeError: Cannot read properties of null (reading 'valid')
    at new n (https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:1946700)
    at n.value (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1963341)
    at new n (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1962325)
    at Object.createNewInstanceRenderer (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1985233)
    at https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:1980574
    at mapReverseFor (https://editor.gdevelop.io/static/js/5496.45f6639a.chunk.js:1:2350186)
 ...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in Nk
    in $k
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in PI
    in div
    in n
    in Ga
    in div
    in _L
    in Unknown
    in mt
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in Re
    in n
    in ut
    in vt
    in t
    in Unknown
    in Unknown
    in v
    in It
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

### PR DESCRIPTION
**Pull request by 4ian**
Fix #5896

### CODE REVIEW

File: newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js [hunk 1]
```diff
@@ -99,13 +99,13 @@ export default class RenderedPanelSpriteInstance extends RenderedInstance {
     this._centerSprite = new StretchedSprite(new PIXI.Texture(texture));
     this._borderSprites = [
       new StretchedSprite(new PIXI.Texture(texture)), //Right
-      new PIXI.Sprite(texture), //Top-Right
+      new PIXI.Sprite(new PIXI.Texture(texture)), //Top-Right
```
Comment (D8H) [inline newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js:102]: Could the fix be not to create a new texture and not to destoy it?
```JS
borderSprite.destroy({ texture: true });
```
```JS
borderSprite.destroy({ texture: false });
```
