### PR TITLE
Fix web debugger icon not updating properly

### LINKED ISSUE #3297: [Web app] Preview button stuck on hot reload after closing the preview window
## Describe the bug
The preview button is stuck in the lightning storm icons (hot reload) after closing the preview window.

https://user-images.githubusercontent.com/1670670/143555492-0abd07f6-b0ad-4cdb-9703-8c43a69ddb84.mp4

## Other details
Web app only, since the preview & debugger improvement.

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fixes #3297

### CODE REVIEW

File: newIDE/app/src/Export/BrowserExporters/BrowserS3PreviewLauncher/BrowserPreviewDebuggerServer.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ const setupWindowClosedPolling = () => {
         );
         if (!Object.keys(previewWindowAndTargetIds).length) {
           clearInterval(windowClosedPollingIntervalId);
+          windowClosedPollingIntervalId = null;
```
Comment (4ian) [inline newIDE/app/src/Export/BrowserExporters/BrowserS3PreviewLauncher/BrowserPreviewDebuggerServer.js:55]: Incredible that this was not done 😵 Thanks for fixing my stuff :D

**Review by 4ian — APPROVED** [review]
