### PR TITLE
Fix crash when trying to access a child of a non existing object in an expression

### LINKED ISSUE #6137: Editor crash - using a non-existing structure property in an expression
### Describe what you were doing when the crash happened

Added ammo[1].max for the value of anything. In this case opacity. If the variable isn't defined it crashes when you click away from the field by doing something like clicking the background or another property box. It seems to be related to arrays of structures. It seems to be in the lost focus part. It happens in the app and while using the online version

app:
https://github.com/4ian/GDevelop/assets/113511006/a61d3fab-ac83-47b2-9d93-0386fbbb4ceb

web:
image

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: ecd1a66a-9f87-4481-a709-225f78b1cb62

RuntimeError: memory access out of bounds
    at wasm://wasm/00b41e4e:wasm-function[832]:0x495ee
    at wasm://wasm/00b41e4e:wasm-function[1266]:0x7cc81
    at wasm://wasm/00b41e4e:wasm-function[2561]:0x18aae7
    at wasm://wasm/00b41e4e:wasm-function[2590]:0x18bc10
    at wasm://wasm/00b41e4e:wasm-function[3968]:0x1c16c8
    at Function.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor.ExpressionCompletionFinder.STATIC_GetCompletionDescriptionsFor [as getCompletionDescriptionsFor] (file:///D:/users/keith/appdata/local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster...

### Additional component context

    in n
    in ForwardRef
    in div
    in s
    in f
    in div
    in div
    in s
    in div
    in ForwardRef
    in t
    in ForwardRef
    in div
    in div
    in a
    in Jg
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in dx
    in t
    in Unknown
    in px
    in t
    in div
    in n
    in l
    in n
    in ForwardRef(Em)
    in n
    in t
    in Unknown
    in QM
    in di...

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #6137

### CODE REVIEW

File: Core/GDCore/IDE/Events/ExpressionVariableParentFinder.h [hunk 1]
```diff
@@ -70,7 +70,8 @@ class GD_CORE_API ExpressionVariableParentFinder
         variableNode(nullptr),
         thisIsALegacyPrescopedVariable(false),
         bailOutBecauseEmptyVariableName(false),
-        legacyPrescopedVariablesContainer(nullptr){};
+        legacyPrescopedVariablesContainer(nullptr),
+        variableAndItsParent{} {};
```
Comment (ClementPasteau) [inline Core/GDCore/IDE/Events/ExpressionVariableParentFinder.h:74]: sorry about formatting, this is the only line changed

File: newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js [hunk 2]
```diff
@@ -193,6 +193,10 @@ export default class ExpressionField extends React.Component<Props, State> {
     }
   }
 
+  componentWillUnmount() {
```
Comment (ClementPasteau) [inline newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js:196]: a react warning was being shown because of the debounce. I assume closing the field faster than having the autocompletion returned triggered it

Comment (4ian) [reply newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js:196]: Always a good idea to cancel a debounce (and to a point, anything async like a promise)

**Review by 4ian — APPROVED** [review]
