### PR TITLE
Fix url params not handled when doinga preview over network

### LINKED ISSUE #8283: Latest version of Gdevelop (5.6.256+) breaks url query param support
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

My companies game relies on using query params to pass data to the game. In version 5.6.257 (editor full version: 5.6.257-675a58ed1f9936250cd6cd71a644e4f33944a0f4, core version: 5.6.257-0) when adding a query param to a games url it will now open the listing directory 

In all previous versions of gdevelop this worked with no issue

### Steps to reproduce

1. Open a game with web preview
2. Add a param to the url ie: `http://urip:2929/?i=123`
3. It will now open the listing directory instead of opening the game like normal
4. http://urip:2929/ will still open the game like normal but yeah it seems like it is treating query params as a route now? 

### GDevelop platform

Desktop

### GDevelop version

5.6.257-0

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>MacOS

*OS Version (e.g. Windows 10, macOS 10.15)*
> MacOS 26.3

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> Firefox, Chrome & Safari

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #8283

### CODE REVIEW

File: newIDE/electron-app/app/ServeFolder.js [hunk 1]
```diff
@@ -38,6 +38,17 @@ module.exports = {
           // be used - and the user can still reload manually on its browser.
           watch: [],
           middleware: [
+            // Handle requests with query parameters by serving index.html
+            // This ensures URLs like http://localhost:2929/?i=123 work correctly
+            function handleQueryParams(req, res, next) {
+              const url = new URL(req.url, `http://${req.headers.host}`);
```
Comment (4ian) [inline newIDE/electron-app/app/ServeFolder.js]: Out of caution, can you add a try catch around this so that if URL throws it still works (url will be unchanged)?

**Comment by 4ian** [comment]
@cursor Out of caution, can you add a try catch around this so that if URL throws it still works (url will be unchanged)?
