### PR TITLE
Fix loading video resources in Runtime

### LINKED ISSUE #5711: Video playback is broken in GDevelop 5.2.173
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Video playback is not working, it just shows a amall pink square instead of a video to be played.
This happens on projects that has had a working video playback for years up to 5.2.172.

### Steps to reproduce

Make a video to playback in a project and try to run it.

### GDevelop platform

Desktop

### GDevelop version

5.2.173

### Platform info

OS: Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fixes #5711

### CODE REVIEW

File: GDJS/Runtime/pixi-renderers/pixi-image-manager.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ namespace gdjs {
     setResources(resourceDataArray: ResourceData[]): void {
       this._resources.clear();
       for (const resourceData of resourceDataArray) {
-        if (resourceData.kind === 'image') {
+        if (resourceData.kind === 'image' || resourceData.kind === 'video') {
```
Comment (AlexandreSi) [inline GDJS/Runtime/pixi-renderers/pixi-image-manager.ts:98]: Is there another resource kind we might have forgotten?

Comment (ClementPasteau) [reply GDJS/Runtime/pixi-renderers/pixi-image-manager.ts:98]: I checked all, and this was the only missing
