### PR TITLE
Fix tabs in preference dialog not always on top

### LINKED ISSUE #3293: "GDevelop Preferences" tabs should always remain at top, even after scrolling down
## Description

Currently, when the user scrolls down the GDevelop Preferences screen, they lose access to the tabs at the top.  The user must scroll up to the top to use these tabs.

https://user-images.githubusercontent.com/8879811/143513470-09bd4fa0-9914-4575-b2c9-2538f60f2a38.mp4

## Solution suggested

"GDevelop Preferences" tabs should always remain at the top, even after scrolling down

### PR DESCRIPTION
**Pull request by Midhil457**
- Removed the `Preference` Title as no other similar dialogs (project properties, profile) had a title text. All of them had the Tabs as title
- Fix Tabs not always on top. Fixes #3293 

Pre-comparision

### CODE REVIEW

File: newIDE/app/src/MainFrame/Preferences/PreferencesDialog.js [hunk 1]
```diff
@@ -67,15 +67,22 @@ const PreferencesDialog = ({ i18n, onClose }: Props) => {
       onRequestClose={onClose}
       cannotBeDismissed={true}
       open
-      title={<Trans>GDevelop Preferences</Trans>}
+      noTitleMargin
       maxWidth="sm"
       noMargin
+      title={
+        <div>
```
Comment (Bouh) [inline newIDE/app/src/MainFrame/Preferences/PreferencesDialog.js:74]: This Div is required ?

File: newIDE/app/src/MainFrame/Preferences/PreferencesDialog.js [hunk 2]
```diff
@@ -67,15 +67,22 @@ const PreferencesDialog = ({ i18n, onClose }: Props) => {
       onRequestClose={onClose}
       cannotBeDismissed={true}
       open
-      title={<Trans>GDevelop Preferences</Trans>}
+      noTitleMargin
```
Comment (Bouh) [inline newIDE/app/src/MainFrame/Preferences/PreferencesDialog.js:70]: 👍

**Review by Bouh — APPROVED** [review]

**Comment by 4ian** [comment]
Thanks, looking better with the tabs staying on top. I've fixed the extra div, looks good to go 👍
