### PR TITLE
Detect all physics collisions

### LINKED ISSUE #4009: Physics behavior not tracking collisions properly.
When collisions happen between frames the physics behavior doesn't count them as collisions, and therefore developers who expect a sound effect or value to change upon collision will be sorely upset.

## To Reproduce
Just play the game at 20 min fps and 20 max fps and compare it to 60/60. There will be missing counts.

[Plinko.zip](https://github.com/4ian/GDevelop/files/8863544/Plinko.zip)

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #4009

### CODE REVIEW

File: Extensions/Physics2Behavior/JsExtension.js [hunk 1]
```diff
@@ -3734,7 +3735,7 @@ module.exports = {
         _('Collision'),
         _('Test if two objects collide.'),
         _('_PARAM0_ is colliding with _PARAM2_'),
-        '',
+        _('Collisions'),
         'res/physics32.png',
```
Comment (D8H) [inline Extensions/Physics2Behavior/JsExtension.js:3739]: The advantage to leave no category is that it is on top of the list. It makes sens as it might be the most used condition.
The group "Collision" (without an "s") could be used to merge it with the built-in conditions.

File: Extensions/Physics2Behavior/JsExtension.js [hunk 2]
```diff
@@ -3746,6 +3747,42 @@ module.exports = {
       .setIncludeFile('Extensions/Physics2Behavior/physics2tools.js')
       .setFunctionName('gdjs.physics2.objectsCollide');
 
+    extension
+      .addCondition(
+        'CollisionStarted',
+        _('Collision start'),
```
Comment (D8H) [inline Extensions/Physics2Behavior/JsExtension.js:3753]: Why not "Collision started"?

File: Extensions/Physics2Behavior/JsExtension.js [hunk 3]
```diff
@@ -3746,6 +3747,42 @@ module.exports = {
...
+      .addCodeOnlyParameter('conditionInverted', '')
+      .getCodeExtraInformation()
+      .setIncludeFile('Extensions/Physics2Behavior/physics2tools.js')
+      .setFunctionName('gdjs.physics2.objectsStartedColliding');
+
+    extension
+      .addCondition(
+        'CollisionStopped',
+        _('Collision stop'),
+        _('Test if two objects stopped colliding.'),
```
Comment (D8H) [inline Extensions/Physics2Behavior/JsExtension.js:3772]: "Test" is used in some conditions but should we replace them by "Check"?

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 4]
```diff
@@ -48,13 +48,25 @@ namespace gdjs {
...
-        behaviorB.currentContacts.push(behaviorA);
+        // There might be contacts that end during the frame and
+        // start again right away. It is considered a glitch
+        // and should not be detected.
+        let i = behaviorA.contactsEndedBetweenFrames.indexOf(behaviorB);
+        if (i !== -1) {
+          behaviorA.contactsEndedBetweenFrames.splice(i, 1);
+        } else {
+          behaviorA.contactsStartedBetweenFrames.push(behaviorB);
+        }
```
Comment (D8H) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:63]: It could be a `onContactBegin` method in the behavior.

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 5]
```diff
@@ -281,7 +288,13 @@ namespace gdjs {
...
       this.layers = behaviorData.layers;
       this.masks = behaviorData.masks;
-      this.currentContacts = this.currentContacts || [];
+      this.contactsStartedBetweenFrames =
+        behaviorData.contactsStartedBetweenFrames || [];
+      this.contactsStartedBetweenFrames.length = 0;
+      this.contactsEndedBetweenFrames =
+        behaviorData.contactsEndedBetweenFrames || [];
+      this.contactsEndedBetweenFrames.length = 0;
+      this.currentContacts = behaviorData.currentContacts || [];
```
Comment (D8H) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:297]: `behaviorData` is for properties.

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 6]
```diff
@@ -741,11 +754,27 @@ namespace gdjs {
...
     }
 
     doStepPostEvents(runtimeScene) {
       this._updateBodyFromObject();
 
+      // Reset contacts that happened in-between frames
+      this.contactsStartedBetweenFrames.splice(
+        0,
+        this.contactsStartedBetweenFrames.length
+      );
```
Comment (D8H) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:772]: Setting the length to `0` is easier to read (maybe faster but I'm not sure)

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 7]
```diff
@@ -3813,6 +3842,70 @@ namespace gdjs {
...
+        // true anyway.
+        for (
+          let i = 0, len = behavior1.contactsStartedBetweenFrames.length;
+          i < len;
+          ++i
+        ) {
+          if (behavior1.contactsStartedBetweenFrames[i].owner === object2) {
+            return true;
+          }
+        }
```
Comment (D8H) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:3856]: `Array.some` could be used.

File: Extensions/Physics2Behavior/JsExtension.js [hunk 8]
```diff
@@ -3746,6 +3747,42 @@ module.exports = {
       .setIncludeFile('Extensions/Physics2Behavior/physics2tools.js')
       .setFunctionName('gdjs.physics2.objectsCollide');
 
+    extension
+      .addCondition(
+        'CollisionStarted',
+        _('Collision start'),
+        _('Test if two objects started colliding.'),
```
Comment (4ian) [inline Extensions/Physics2Behavior/JsExtension.js:3754]: We generally now prefer "Check" or "Compare" over "Test".

```suggestion
        _('Check if two objects started colliding.'),
```

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts (hunk 5 above)
Comment (4ian) [reply Extensions/Physics2Behavior/physics2runtimebehavior.ts:297]: Yes no need to initialise from anything, just set it to `[]`.

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 9]
```diff
@@ -3813,6 +3842,70 @@ namespace gdjs {
...
+      }
+
+      // No contact found
+      return false;
+    }
+
+    // Collision
+    static stoppedCollisionTest(
```
Comment (4ian) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:3890]: ditto

File: Extensions/Physics2Behavior/physics2tools.ts [hunk 10]
```diff
@@ -15,6 +15,36 @@ namespace gdjs {
       );
     };
 
+    export const objectsStartedColliding = function (
```
Comment (4ian) [inline Extensions/Physics2Behavior/physics2tools.ts:18]: haveObjectsStartedColliding?
and (haeObjectsStoppedColliding)?

File: Extensions/Physics2Behavior/JsExtension.js [hunk 11]
```diff
@@ -3746,6 +3747,42 @@ module.exports = {
...
+      .addParameter('objectList', _('Object'), '', false)
+      .addCodeOnlyParameter('conditionInverted', '')
+      .getCodeExtraInformation()
+      .setIncludeFile('Extensions/Physics2Behavior/physics2tools.js')
+      .setFunctionName('gdjs.physics2.objectsStartedColliding');
+
+    extension
+      .addCondition(
+        'CollisionStopped',
+        _('Collision stop'),
```
Comment (4ian) [inline Extensions/Physics2Behavior/JsExtension.js:3771]: `Collision stopped`?

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts (hunk 6 above)
Comment (4ian) [reply Extensions/Physics2Behavior/physics2runtimebehavior.ts:772]: Yep, use `length = 0`, this is handled well by JS engines.

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 12]
```diff
@@ -241,6 +246,8 @@ namespace gdjs {
     layers: any;
     masks: any;
     shapeScale: number = 1;
+    contactsStartedBetweenFrames: Array<any>;
+    contactsEndedBetweenFrames: Array<any>;
```
Comment (4ian) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:250]: Because there is nothing really "between frames" (something is always computed as part of the rendering of a frame), I would rather name these:

```suggestion
    contactsStartedThisFrame: Array<any>;
    contactsEndedThisFrame: Array<any>;
```

or 

```suggestion
    contactsJustStarted: Array<any>;
    contactsJustEnded: Array<any>;
```

Indeed, the simulation of the physics engine is done just before the events (in the do pre events). So the contacts are really detected as starting/ending when simulating *this* frame?

Wdyt @D8H @AlexandreSi ?

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 13]
```diff
@@ -0,0 +1,108 @@
...
+      items,
+      startedItems,
+      endedItems
+    );
+    for (let i = 0; i < items.length; i++) {
+      expect(items[i]).to.be(expectedResolvedItems[i]);
+    }
+  });
+
+  it('It returns current items with item started twice', () => {
```
Comment (4ian) [inline Extensions/Physics2Behavior/tests/utils.spec.js:79]: ubernit:
```suggestion
  it('returns current items with item started twice', () => {
```

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 14]
```diff
@@ -0,0 +1,108 @@
...
+    const items = ['A', 'B', 'C'];
+    const startedItems = ['Z', 'Z'];
+    const endedItems = ['Z'];
+    const expectedResolvedItems = [...items, 'Z'];
+    gdjs.physics2.computeCurrentContactsFromStartedAndEndedContacts(
+      items,
+      startedItems,
+      endedItems
+    );
+    for (let i = 0; i < items.length; i++) {
```
Comment (4ian) [inline Extensions/Physics2Behavior/tests/utils.spec.js:89]: Try (I'm not sure): `expect(items).to.eql(expectedResolvedItems)`

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 15]
```diff
@@ -3813,6 +3842,70 @@ namespace gdjs {
             return true;
           }
         }
+        // If a contact has started between frames and ended right away, it
```
Comment (4ian) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:3845]:
```suggestion
        // If a contact has started at this frame and ended right away, it
```

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts (hunk 4 above)
Comment (AlexandreSi) [reply Extensions/Physics2Behavior/physics2runtimebehavior.ts:63]: Great idea, I'll do this

File: Extensions/Physics2Behavior/utils.ts [hunk 16]
```diff
@@ -0,0 +1,25 @@
+namespace gdjs {
+  export namespace physics2 {
+    export const computeCurrentContactsFromStartedAndEndedContacts = <T>(
+      current: Array<T>,
+      started: Array<T>,
+      ended: Array<T>
+    ): void => {
```
Comment (D8H) [inline Extensions/Physics2Behavior/utils.ts:7]: It was extracted to be able to test it?

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts (hunk 6 above)
Comment (D8H) [reply Extensions/Physics2Behavior/physics2runtimebehavior.ts:772]: The arrays can be cleared at the beginning of `doStepPreEvents`. It will allow to write tests more easily. It won't change how it behaves as these arrays are not used during the rending.

**Review by 4ian — APPROVED** [review]
LGTM

File: Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js [hunk 17]
```diff
@@ -0,0 +1,128 @@
+// TODO: find a way to add assertions at events time to enable this test.
+describe.skip('Physics2RuntimeBehavior', () => {
```
Comment (D8H) [inline Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js:2]: This needs to be addressed.
Arrays clearing can be done at the beginning of the preEvent function.

Comment (AlexandreSi) [reply Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js:2]: The conditions use the functions `hasCollisionStartedBetween` and `hasCollisionStoppedBetween`, and themselves use the arrays `contactsStartedThisFrame` and `contactsStoppedThisFrame` so I can't erase them in the pre events, or is there something that I'm missing?

Comment (D8H) [reply Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js:2]: It can be in this order:
- preEvent
  - clear the arrays
  - step Box2d (this fill the arrays)
- events (conditions use the arrays)
loop...

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 18]
```diff
@@ -0,0 +1,94 @@
+// @ts-check
+
+describe('computeCurrentContactsFromStartedAndEndedContacts', () => {
+  it('returns same current items is nothing happened', () => {
```
Comment (fannieyan) [inline Extensions/Physics2Behavior/tests/utils.spec.js:4]:
```suggestion
  it('returns same current items if nothing happened', () => {
```

**Review by fannieyan — COMMENTED** [review]
Very interesting read!

**Review by 4ian — APPROVED** [review]
lgtm

File: Extensions/Physics2Behavior/physics2runtimebehavior.ts [hunk 19]
```diff
@@ -3797,27 +3811,89 @@ namespace gdjs {
...
+      // There might be contacts that end during the frame and
+      // start again right away. It is considered a glitch
+      // and should not be detected.
+      let i = this.contactsEndedThisFrame.indexOf(otherBehavior);
+      if (i !== -1) {
+        this.contactsEndedThisFrame.splice(i, 1);
+      } else {
+        this.contactsStartedThisFrame.push(otherBehavior);
+      }
+    }
```
Comment (D8H) [inline Extensions/Physics2Behavior/physics2runtimebehavior.ts:3824]: I wonder if it could be interesting to test it as it needed a comment, but I don't see how to write a good test. It will be hard to cover this case with actual physics. I guess, it could be called directly by the test.

**Review by D8H — APPROVED** [review]

File: Extensions/Physics2Behavior/utils.ts [hunk 20]
```diff
@@ -0,0 +1,25 @@
...
+        }
+      });
+      endedDuplicate.forEach((endedItem) => {
+        const index = current.indexOf(endedItem);
+        if (index !== -1) {
+          current.splice(index, 1);
+        }
+      });
+    };
+  }
```
Comment (D8H) [inline Extensions/Physics2Behavior/utils.ts:24]: I think that this method could be much simpler.

End events are eaten by a following start event.
```
[end start]
start [end start]
start [end start] end
[end start] end
```
This means that a `start` is always before a `end`. It could be 2 simple steps:
- add started contacts
- remove ended contacts

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 21]
```diff
@@ -0,0 +1,94 @@
...
+      endedItems
+    );
+    expect(items).to.eql(expectedResolvedItems);
+  });
+
+  it('It returns current items without item ended twice', () => {
+    const items = ['A', 'B', 'C'];
+    const startedItems = ['C'];
+    const endedItems = ['C', 'C'];
+    const expectedResolvedItems = ['A', 'B'];
```
[the remark this answers is not in the document]
Comment (AlexandreSi) [reply Extensions/Physics2Behavior/tests/utils.spec.js:86]: I'm not sure I understood all you meant, but I pushed another version, let me know if it's okay for you

File: Extensions/Physics2Behavior/utils.ts [hunk 22]
```diff
@@ -0,0 +1,25 @@
+namespace gdjs {
+  export namespace physics2 {
+    export const computeCurrentContactsFromStartedAndEndedContacts = <T>(
+      current: Array<T>,
+      started: Array<T>,
+      ended: Array<T>
+    ): void => {
+      const endedDuplicate = [...ended];
```
[the remark this answers is not in the document]
Comment (AlexandreSi) [reply Extensions/Physics2Behavior/utils.ts:8]: I didn't know about it, thanks!

File: Extensions/Physics2Behavior/utils.ts (hunk 20 above)
Comment (AlexandreSi) [reply Extensions/Physics2Behavior/utils.ts:24]: I'll dig into it

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 23]
```diff
@@ -0,0 +1,104 @@
...
+    );
+    expect(contacts).to.eql(expectedResolvedContacts);
+  });
+
+  it('returns current contacts without a contact that ended and also jittered', () => {
+    // Should handle cases where contact C was here and, during the frame:
+    // - contact C ends
+    // - contact C starts
+    // - contact C ends
+    // Contact C should not appear in the current contacts
```
Comment (D8H) [inline Extensions/Physics2Behavior/tests/utils.spec.js:92]: Same.

File: Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js [hunk 24]
```diff
@@ -0,0 +1,269 @@
...
+  });
+
+  describe('onContactBegin', () => {
+    let runtimeGame;
+    let runtimeScene;
+    beforeEach(() => {
+      [runtimeGame, runtimeScene] = createGameWithSceneWithPhysics2SharedData();
+    });
+
+    it('should add behavior to list of started contacts', () => {
```
Comment (D8H) [inline Extensions/Physics2Behavior/tests/physics2runtimebehavior.spec.js:225]: a description like:
"can detect a contact that start during a physic sub steps"
?

Maybe this test could do a "end" after the "beginning" to show that it's keep in this order?
Something like "detect a contact that is maintained only during some physics intermediate sub-steps" ?

File: Extensions/Physics2Behavior/tests/utils.spec.js [hunk 25]
```diff
@@ -0,0 +1,104 @@
...
+      startedContacts,
+      endedContacts
+    );
+    expect(contacts).to.eql(expectedResolvedContacts);
+  });
+
+  it('returns current contacts with ended contacts removed', () => {
+    const contacts = ['A', 'B', 'C', 'Z'];
+    const startedContacts = [];
+    const endedContacts = ['Z', 'B', 'R'];
```
Comment (D8H) [inline Extensions/Physics2Behavior/tests/utils.spec.js:33]: The 'R' can't be removed if it doesn't exist. Every case that can't happens should probably be in a specific describe to make it easier for the reader to understand how the behavior works.

Comment (AlexandreSi) [reply Extensions/Physics2Behavior/tests/utils.spec.js]: I'm not keen on listing things that can't happen somewhere because some things will be forgotten and it can be misleading in the future.
