### PR TITLE
Delete files not existent in project directory

### LINKED ISSUE #4120: Renaming scenes/external events creates duplicate files in the project directory
## Describe the bug
When a project uses the 'multiple files' setting, and you rename a scene or external event from the UI, a new file is created in the project directory (as expected), but the old one remains too. This causes duplicates and confusion.

## To Reproduce
1. Create a new, blank project and set the 'Project file type' setting/property to 'Multiple files'
2. Create a scene and an external event (leave them with the default names
3. Save and verify the correct files are in the project directory
4. Rename the scene and external event
5. Save and check the project directory - note the old files are there along with the new ones

image

image

image

image

## Other details
GDevelop v5.0.138 running on Manjaro Linux (KDE Plasma v5.24.6)

### PR DESCRIPTION
**Pull request by DavidMLPalma**
Fix #4120 : When renaming scenes/extensions/external events/external layouts, duplicate files exist, one with the old name and one with the new name. Similarly, when deleting this items, the respective files are also not removed from the project directory. This is due to the fact that when saving the project, only the existing files in the project editor are written and saved, and nothing more is done.  There may still remain old files that should not be there, potentially creating duplicates and confusion. Therefore, when saving, we can resolve this issue by deleting all files from the scenes/extensions/external events/external layouts directories, before writing the correct files.

### CODE REVIEW

**Comment by AlexandreSi** [comment]
Hi @DavidMLPalma,
Rhanks for the suggested PR!

I feel like this strategy is a bit brutal. We already have issues with users saving their projects in the installation directory and losing their projects because of that (when GDevelop is updated). So I think it's better not to have another potential cause for losing files.

May I suggest that you check if the directory name is in the list `splittedProjectFolderNames` in `LocalProjectWriter`?

**Comment by DavidMLPalma** [comment]
Hi @AlexandreSi ,
Thanks for your reply!

I totally get your point, and in fact by checking if the directory name is one of those present in the list may lead to a more secure solution. I will change it then.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 1]
```diff
@@ -142,6 +168,12 @@ export const onSaveProject = (
   };
 
   const projectPath = path.dirname(filePath);
+
+  deleteExistingFilesFromDirs(projectPath).catch(err => {
+    console.error('Unable to delete files in the project:', err);
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:173]: I think here we could gain clarity if you mention the context: `Unable to clean project folder before saving project:`

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 2]
```diff
@@ -24,6 +24,32 @@ export const splittedProjectFolderNames = [
   'eventsFunctionsExtensions',
 ];
 
+const deleteExistingFilesFromDirs = (projectPath: string) => {
+  const entries = fs.readdirSync(projectPath);
+  return new Promise((resolve, reject) => {
+    //Project file
+    if (entries.length === 1) resolve();
+
+    //If multiFile enabled in settings and directories exist!
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:33]: You do not actually check if multifile is enabled in the project's settings. You should use `project.isFolderProject()` for that.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 3]
```diff
@@ -24,6 +24,32 @@ export const splittedProjectFolderNames = [
   'eventsFunctionsExtensions',
 ];
 
+const deleteExistingFilesFromDirs = (projectPath: string) => {
+  const entries = fs.readdirSync(projectPath);
+  return new Promise((resolve, reject) => {
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:29]: You don't need to use promises here, all the filesystem methods you use are synchronous.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 4]
```diff
@@ -24,6 +24,32 @@ export const splittedProjectFolderNames = [
...
+      let dirPath = projectPath.concat('\\', entry);
+      if (
+        fs.statSync(dirPath).isDirectory() &&
+        splittedProjectFolderNames.includes(entry)
+      ) {
+        const filenames = fs.readdirSync(dirPath);
+        filenames.forEach(file => {
+          let result = dirPath.concat('\\', file);
+          fs.unlink(result, err => {
+            if (err) return reject(err);
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:44]: You could add context here, such as:
```
throw new Error(`Unable to remove file ${file}: ${err.message}`
```
Or something like that

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js (hunk 3 above)
Comment (AlexandreSi) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:29]: (I think `fs.unlinkSync` also exists)

**Comment by DavidMLPalma** [comment]
Hi @AlexandreSi ,
Thanks a lot for the patience and feedback! I will try to implement all the things you pointed out !

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 5]
```diff
@@ -142,6 +168,12 @@ export const onSaveProject = (
   };
 
   const projectPath = path.dirname(filePath);
+
+  deleteExistingFilesFromDirs(projectPath).catch(err => {
```
[the remark this answers is not in the document]
Comment (AlexandreSi) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js]: No, I think it's okay to keep it synchronous

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js (hunk 2 above)
Comment (AlexandreSi) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:34]: To make it one step clearer by removing the indent, you could do this:

```js
if (!project.isFolderProject()) return;

const entries = fs.readdirSync(projectPath);
...
```

Also, I'm not sure this comment is useful anymore, your code is quite clear.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 6]
```diff
@@ -24,6 +24,34 @@ export const splittedProjectFolderNames = [
...
+const deleteExistingFilesFromDirs = (
+  project: gdProject,
+  projectPath: string
+) => {
+  const entries = fs.readdirSync(projectPath);
+
+  if (project.isFolderProject()) {
+    //If multiFile enabled in settings and directories exist!
+    entries.forEach(entry => {
+      let dirPath = projectPath.concat('\\', entry);
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:36]: I forgot to check how you handle paths: Using strings that you concat yourself won't work because Windows user `\` separator while Linux and macOS user `/`. So you should use `path.join` instead. You can find other users of path in the codebase.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 7]
```diff
@@ -24,6 +24,34 @@ export const splittedProjectFolderNames = [
...
+      if (
+        fs.statSync(dirPath).isDirectory() &&
+        splittedProjectFolderNames.includes(entry)
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:39]: You could use this condition as an early return as well:

```js
if (splittedProjectFolderNames.includes(entry)) return;
let dirPath = projectPath.concat('\\', entry);
...
```

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js (hunk 6 above)
Comment (AlexandreSi) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:36]: Furthermore, you can use `const` instead of `let` since you never reassign the variable value

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 8]
```diff
@@ -24,6 +24,34 @@ export const splittedProjectFolderNames = [
...
+      ) {
+        const filenames = fs.readdirSync(dirPath);
+        filenames.forEach(file => {
+          let result = dirPath.concat('\\', file);
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:43]: You could rename `result` with a name that actually represents what it is: `filePath` or `fileToRemovePath`

**Comment by DavidMLPalma** [comment]
Hi @AlexandreSi ,

Once again, thanks for your help and consideration !

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 9]
```diff
@@ -142,9 +168,20 @@ export const onSaveProject = (
...
 
   const projectPath = path.dirname(filePath);
-  return writeProjectFiles(project, filePath, projectPath).then(() => {
-    return { wasSaved: true, fileMetadata: newFileMetadata }; // Save was properly done
-  });
+
+  try {
+    deleteExistingFilesFromDirs(project, projectPath);
+  } catch (e) {
+    return Promise.reject(
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:175]: I think that deleting the existing files from the folders should fail silently.
You can `console.warn` a message but stopping a save could mean preventing a user from saving if an error happens.

Comment (AlexandreSi) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:175]: Also, since you made the change to an async function (thank you!), could you replace the `return new Promise.reject` line 158 by a `throw new Error('...')`

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js [hunk 10]
```diff
@@ -24,6 +24,32 @@ export const splittedProjectFolderNames = [
...
+) => {
+  //If multiFile is not enabled in settings and directories do not exist.
+  if (!project.isFolderProject()) return;
+
+  const entries = fs.readdirSync(projectPath);
+  entries.forEach(entry => {
+    if (!splittedProjectFolderNames.includes(entry)) return;
+
+    const dirPath = path.join(projectPath, entry);
+    if (fs.statSync(dirPath).isDirectory()) {
```
Comment (AlexandreSi) [inline newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js:39]: You can also replace the added intent by an early return here.

File: newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js (hunk 9 above)
Comment (DavidMLPalma) [reply newIDE/app/src/ProjectsStorage/LocalFileStorageProvider/LocalProjectWriter.js]: Done !

**Review by AlexandreSi — APPROVED** [review]
LGTM!
Thanks for staying with me though I asked for a lot of changes. I hope our coding style is clearer to you today!
