### PR TITLE
Fix crash on empty while event

### LINKED ISSUE #2437: [$45 bounty] Empty while block stuck loading game
## Describe the bug
An empty while event in an empty project crash the game.
I can't see errors in debugger or console because i think there is an infinite loop.
So here the code from the temp folder:

```JS
gdjs.New_32sceneCode = {};
gdjs.New_32sceneCode.stopDoWhile2 = false;


gdjs.New_32sceneCode.conditionTrue_0 = {val:false};
gdjs.New_32sceneCode.condition0IsTrue_0 = {val:false};


gdjs.New_32sceneCode.eventsList0 = function(runtimeScene) {

};gdjs.New_32sceneCode.eventsList1 = function(runtimeScene) {

{


gdjs.New_32sceneCode.stopDoWhile2 = false;
do {if (true) {
if (true) {

{ //Subevents: 
gdjs.New_32sceneCode.eventsList0(runtimeScene);} //Subevents end.
}
} else gdjs.New_32sceneCode.stopDoWhile2 = true; 
} while ( !gdjs.New_32sceneCode.stopDoWhile2 );

}


};

gdjs.New_32sceneCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();


gdjs.New_32sceneCode.eventsList1(runtimeScene);
return;

}

gdjs['New_32sceneCode'] = gdjs.New_32sceneCode;

```

image

## Other details
* b105, b106
[Source: forum](https://forum.gdevelop-app.com/t/empty-while-block-stuck-loading-game/31343)

### PR DESCRIPTION
**Pull request by arthuro555**
Fixes #2437 

Doesn't generate while events without any conditions as it is impossible to break out of them and crashes the game. If you really wish to crash the game, you can still put the always condition in the while event.

### CODE REVIEW

File: GDJS/GDJS/Extensions/Builtin/CommonInstructionsExtension.cpp [hunk 1]
```diff
@@ -347,11 +347,18 @@ CommonInstructionsExtension::CommonInstructionsExtension() {
...
-        gd::String outputCode;
         gd::WhileEvent& event = dynamic_cast<gd::WhileEvent&>(event_);
 
-        // Context is "reset" each time the event is repeated (i.e. objects are
-        // picked again)
+        // Prevent code generation if there are no conditions, as this would
+        // get the game stuck in a never ending loop.
+        if (event.GetWhileConditions().empty())
+          return gd::String(
+              "\n// While event not generated to prevent a crash\n");
```
Comment (4ian) [inline GDJS/GDJS/Extensions/Builtin/CommonInstructionsExtension.cpp:356]: nitpicking: `infinite loop` instead of crash.

File: GDJS/GDJS/Extensions/Builtin/CommonInstructionsExtension.cpp [hunk 2]
```diff
@@ -347,11 +347,18 @@ CommonInstructionsExtension::CommonInstructionsExtension() {
...
          gd::EventsCodeGenerator& codeGenerator,
          gd::EventsCodeGenerationContext& parentContext) {
-        gd::String outputCode;
         gd::WhileEvent& event = dynamic_cast<gd::WhileEvent&>(event_);
 
-        // Context is "reset" each time the event is repeated (i.e. objects are
-        // picked again)
+        // Prevent code generation if there are no conditions, as this would
+        // get the game stuck in a never ending loop.
+        if (event.GetWhileConditions().empty())
```
Comment (4ian) [inline GDJS/GDJS/Extensions/Builtin/CommonInstructionsExtension.cpp:354]: I would also check for the conditions and actions inside the while, if absolutely everything is empty.

The idea is to avoid bug reports because "while does not work". It should just do nothing when there is nothing at all.

**Review by 4ian — COMMENTED** [review]
That was quick :)

**Comment by arthuro555** [comment]
> That was quick :)

I was already coding (working in GDMod) and "in the flow" when I received a GitHub notification about this easy fix so I figured I'd look into it.

**Review by 4ian — APPROVED** [review]
