### PR TITLE
Fix outdated data

### LINKED ISSUE #5078: New object Groups not updating on External Layouts immediately
## Describe the bug

New object Groups not updating on External Layouts immediately.
The group names were corrupted until clicking on them.

## To Reproduce
1) Create a scene and an external layout linked to that scene.
2) Add new object groups to the primary scene
3) Open external layout and see corrupt Object group names
4) Clicking on object groups fixes them

https://user-images.githubusercontent.com/8879811/223860409-5b08566f-bb36-4386-a35f-771cb3a6d9bc.mp4

## Other details
* Windows 11
* GDevelop 5.1.158

### PR DESCRIPTION
**Pull request by AlexandreSi**
- Update resource preview on property change (really useful to see the change when clicking on "Smooth the image")
- Update object groups when scene editor becomes active again (Resolves #5078)

### CODE REVIEW

**Review by ClementPasteau — APPROVED** [review]
lgtm, i'm wondering if there is a deeper cause as to why they don't refresh, but the forceUpdates are done in a controlled way, so I think we're fine.

File: newIDE/app/src/SceneEditor/index.js [hunk 1]
```diff
@@ -225,6 +226,9 @@ export default class SceneEditor extends React.Component<Props, State> {
     if (this.state.history !== prevState.history)
       if (this.props.unsavedChanges)
         this.props.unsavedChanges.triggerUnsavedChanges();
+    if (!prevProps.isActive && this.props.isActive) {
+      if (this._objectGroupsList) this._objectGroupsList.forceUpdate();
```
Comment (4ian) [inline newIDE/app/src/SceneEditor/index.js:230]: I suggest we rather modify this method:
image


and update comment:
image

so we stay consistent with how the objects list is also force updated. (or adapt the objects list so that it's force updated like you did, and clean the forceUpdateEditor if not required anymore)

Comment (AlexandreSi) [reply newIDE/app/src/SceneEditor/index.js:230]: Oh good idea!

Comment (4ian) [reply newIDE/app/src/SceneEditor/index.js:230]: To be honest, the way it's done for objects list is harder maybe to discover, because it's done outside the component (so it's more imperative than what you did).
But at least it will be consistent and easy to find where these force updates are done :)
