### PR TITLE
Fix spinner issue in "See all my builds"

### LINKED ISSUE #1541: Spinner under "All your builds" dialog spins forever in case of no builds
## Describe the bug
The spinner under "All your builds" dialog spins forever in case of no previous builds. 

Expected behaviour :
It should spin for few seconds and alert the user that there are no builds.

## To Reproduce
1. Create a new project
2. Export project
3. Click "See all my builds" in the export dialog
4. See bug

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.
Screenshot 2020-03-17 at 1 45 33 PM

## Other details
* Include any OS/browser version/smartphone that you're using - Mac OSX Mojave, Firefox 74.0 (64-bit)
* Which version of GDevelop are you using? The desktop app or the web-app? Web-app
* Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by pranavmodx**
Fixes #1541 
Also fixed a small grammatical error in a message.

### CODE REVIEW

File: newIDE/app/src/Export/Builds/BuildsList.js [hunk 1]
```diff
@@ -41,27 +43,33 @@ const formatBuildText = (
...
+export default ({ builds, userProfile, onDownload }: Props) => {
   return (
     <Column noMargin expand>
       <Line>
         <Column>
           <EmptyMessage>
             <Trans>
               This is the list of builds that you've done. Note that you can
-              download games generated during to 7 days, after which they are
+              download games generated during last 7 days, after which they are
```
Comment (PawBud) [inline newIDE/app/src/Export/Builds/BuildsList.js]: I think it should be **download games generated during the last 7 days, after which they are**. Because then it sounds grammatically correct

**Comment by 4ian** [comment]
That looks correct, thanks for the PR :) Be sure to run auto formatting (search the README how to run it).

File: newIDE/app/src/Export/Builds/BuildsList.js (hunk 1 above)
Comment (4ian) [reply newIDE/app/src/Export/Builds/BuildsList.js]: Yep, "during the last 7 days" sounds better.

**Comment by 4ian** [comment]
Looks good, thanks 👍
