### PR TITLE
Fix calling methods on Texture frame which can be null when an image is updated

### LINKED ISSUE #5877: Crash after editing sprite (Manual Report link didn't work)
### Describe what you were doing when the crash happened

SORRY IF THIS REPORT SUCKS SINCE THE LINK DIDNT WORK SO I HAD TO SUBMIT THE ISSUE THROUGH MY REPO FIRST TO GET THE CONTENTS

(PLEASE CHECK IF YOU ARE REFRENCING THIS AUTOMATIC CRASH REPORT CATEGORY) (in link ofc)

1. Made an object
2. Created Sprite
3. added logic to make it point towards the cursor
4. changed sprite
5. crash in editor

### GDevelop version

5.3.180.0 (MS store)

## Other details
* IDE version: 5.3.180-8dbf9c99ce5a0fe0417c0cb09302abcbc974d172
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19045,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.180 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of null (reading 'width')
    at n.value (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/5496.6be983ec.chunk.js:1:1953923)
    at e.getUnrotatedInstanceSize (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/5496.6be983ec.chunk.js:1:1340287)
    at Object.getUnrotatedInstanceSize (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.3.180.0_x64__k1pbm4zg68kra/app/resources/app.a...
```

## Component stack (don't write anything here)
```

    in e
    in div
    in s
    in f
    in e
    in div
    in s
    in div
    in s
    in div
    in ForwardRef
    in ck
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Ff
    in ForwardRef
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in y
    in t
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in aI
    in div
    in n
    in Na
    in div
    in xL
    in Unknown
    in mt
    in f
    in u
    in v
    in m
...

### PR DESCRIPTION
**Pull request by ClementPasteau**
Trying to fix #5877 

Capture d’écran 2023-11-06 à 16 54 44

### CODE REVIEW

File: GDJS/Runtime/pixi-renderers/spriteruntimeobject-pixi-renderer.ts [hunk 1]
```diff
@@ -54,22 +54,21 @@ namespace gdjs {
      * Update the internal PIXI.Sprite position, angle...
      */
     _updatePIXISprite() {
-      if (this._object._animationFrame !== null) {
+      const spriteTextureFrame = this._sprite.texture.frame;
```
Comment (4ian) [inline GDJS/Runtime/pixi-renderers/spriteruntimeobject-pixi-renderer.ts:57]: I think we've never observed the problem at runtime, and runtime should never have the problem because textures must always be loaded beforehand... I would not include this change then. cc @D8H

Comment (AlexandreSi) [reply GDJS/Runtime/pixi-renderers/spriteruntimeobject-pixi-renderer.ts:57]: I agree

**Comment by 4ian** [comment]
As discussed:
- Let's remove the runtime changes
- ErrorBoundary can be added (with other PRs) in more part of the app so we have more fine grained error reports and avoid crashing the entire app if something goes wrong for example in a tab or a dialog.
