### PR TITLE
Prevent opening variables dialog for objects & groups if there is no object

### LINKED ISSUE #7129: Variables crash
### Describe what you were doing when the crash happened

**1-** Create a new object (any type).
**2-** Open events.
**3-** Use Condition or action object variable.
**4-** Declare that object variable.
**5-** Delete the object.
**6-** Go back to events.
**7-** Select the variable and click (Add or edit variables).
**8-** Crash !

### GDevelop version

Latest released one (auto update not manual)

### Platform info

_No response_

### Additional error context

_No response_

### Additional component context

_No response_

### PR DESCRIPTION
**Pull request by ClementPasteau**
Fix #7129

### CODE REVIEW

File: newIDE/app/src/EventsSheet/ParameterFields/ObjectVariableField.js [hunk 1]
```diff
@@ -188,37 +188,43 @@ export default React.forwardRef<ParameterFieldProps, ParameterFieldInterface>(
...
+              initiallySelectedVariableName={editorOpen.variableName}
+              shouldCreateInitiallySelectedVariable={editorOpen.shouldCreate}
+              onComputeAllVariableNames={onComputeAllVariableNames}
+              hotReloadPreviewButtonProps={null}
+            />
+          )}
+        {editorOpen &&
+          project &&
+          objectGroup &&
+          !!variablesContainers.length && (
```
Comment (4ian) [inline newIDE/app/src/EventsSheet/ParameterFields/ObjectVariableField.js:213]: Sounds suspicious as not used then?

**Review by 4ian — APPROVED** [review]
