### PR TITLE
Fix treeview search crash when global objects placeholder is displayed

### LINKED ISSUE #5862: Search in Objects Pane Caused a "Problem"
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I click into "Search Objects" and the cursor appears. I start typing and--no matter what I type--I get "editor encountered a problem" immediately and have to restart the engine.

### Steps to reproduce

1. Open Scene
2. Click into "Search Objects"
3. Press any key

### GDevelop platform

Desktop

### GDevelop version

editor full version: 5.3.179-e0df9b0ff39dcea7a28e6baeb1de814b8acd3399, core version: 4.0.99-0-release

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #5862

### CODE REVIEW

File: newIDE/app/src/UI/TreeView/index.js [hunk 1]
```diff
@@ -235,7 +235,7 @@ const TreeView = <Item: ItemBaseAttributes>(
         !searchText ||
         forceAllOpened ||
         forceOpen ||
-        name.toLowerCase().includes(searchText) ||
```
Comment (ClementPasteau) [inline newIDE/app/src/UI/TreeView/index.js:238]: in which case do we have a React.Node? 
Does this mean in this case the search will not work?

Comment (AlexandreSi) [reply newIDE/app/src/UI/TreeView/index.js:238]: Only for the placeholders. The scene object placeholder is done through `i18n._(...)` and the search works for this.
But for the global object placeholder, since we want to have a link inside, I had to use `<Trans>...<Trans />`. That's the only case.

Comment (ClementPasteau) [reply newIDE/app/src/UI/TreeView/index.js:238]: ok then 👍

**Review by ClementPasteau — APPROVED** [review]
