### PR TITLE
Automatically fix object/group/function/behavior/object/property names when an incorrect one is entered

### LINKED ISSUE #5557: Component improvement: Display "invalid name" erro under text field, instead of closing the wondow.
The system does not accept spaces on Object numbers.
Today, if a user (who's still acquiring the reflex to not to write spaces) adds a space, the system gives an "invalid name" pop-up message, and closes the object dialog:
Screenshot 2023-08-11 at 13 05 58

This means that the user has to open the object dialog *again* to change the name.

**Suggestion:**
The user should be able to delete their space on the field without the system kicking them out of the modal.
An "input error" with the error type is suggested to prevent any further errors.
Screenshot 2023-08-11 at 13 07 44

This means that the user con't be able to "Accept" on the modal if the name hasn't been corrected.

### PR DESCRIPTION
**Pull request by 4ian**
And also for scenes, external events, external layouts and extensions in the project manager.

This removes all the "flow breaking" message boxes. While this might make the reason for the renaming harder to understand, I think it will be well understood. For example in Figma, if you rename a shape to an empty string, it will override it with a default name.
In the future, we could show a snack bar at the bottom that gives an explanation, but not even sure it's required (could be added in the docs, and that's it - the important is that GDevelop fixes the name for you).

Fix #5557

### CODE REVIEW

File: Core/GDCore/Project/Project.cpp [hunk 1]
```diff
@@ -1003,6 +1003,26 @@ bool Project::ValidateName(const gd::String& name) {
...
+  if (isdigit(name[0])) newName = "_" + newName;
+
+  gd::String allowedCharacters =
+      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_";
+  
+  for (size_t i = 0;i < newName.size();++i) {
+    // Replace all unallowed letters by an underscore.
+    if (allowedCharacters.find_first_of(std::u32string(1, newName[i])) == gd::String::npos) {
+      newName.replace(i, 1, '_');
+    }
```
Comment (D8H) [inline Core/GDCore/Project/Project.cpp:1020]: What if none of the characters are safe?
Should the renaming be aboorted rather than using `_______`?
