### PR TITLE
Fix URL opening action on iOS

### LINKED ISSUE #6154: iOS does not open URLs
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Good Morning,

I've noticed that when I publish my app on iOS, it can't open the links. I have social media links (to try to open the app or the browser) and links that require the browser because it is a website. 

Apparently they don't work for iOS and there aren't many options to open the links. Does the URL have to contain a specific format?

Captura de pantalla 2024-01-08 083213
Captura de pantalla 2024-01-08 083301

Thank you for your help.

### Steps to reproduce

Click on an image and access to the URL. Only doesn't work for iOS

### GDevelop platform

Mobile

### GDevelop version

5.3.186

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlexandreSi**
Fixes #6154 
- Tested on iOS simulator (iPhone 14) to make sure the URL is opened
- Tested on Android simulator (Pixel 5) to make sure the URL is still opened
- Tested on web build (Chrome) to make sure the URL is still opened

### CODE REVIEW

File: GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.ts [hunk 1]
```diff
@@ -859,10 +859,12 @@ namespace gdjs {
         const electron = this.getElectron();
         if (electron) {
           electron.shell.openExternal(url);
-        } else {
           // @ts-ignore
-          const target = window.cordova ? '_system' : '_blank';
-          window.open(url, target);
+        } else if (typeof window.cordova !== 'undefined') {
```
Comment (4ian) [inline GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.ts:863]: To be 100% safe, might be worth checking if `typeof window.cordova.InAppBrowser !== 'undefined'`?

**Review by 4ian — APPROVED** [review]
