### PR TITLE
UI improvements

### LINKED ISSUE #3085: Project name overflowing in project manager
## Describe the bug
The project name at the top of the project manager overflows when the project name is long

## To Reproduce
1. Go to project manager
2. Rename the project's name to something long
3. Reopen the project manager (This might also be a bug, the project manager needs to be reopern for the project name to update in the UI)
4. See the overflow of the text

Project=name overflow-syndrome

## Other details
* Linux mint 20.2
* beta177, desktop

One fix might be to add `...` if the project name is too long
Like done here:
sol

Also, maybe limit the project name to maybe 100 characters
:)

### PR DESCRIPTION
**Pull request by AlexandreSi**
Resolves #3085 #2656 #3003

### CODE REVIEW

File: newIDE/app/src/UI/DrawerTopBar.js [hunk 1]
```diff
@@ -43,9 +50,11 @@ export default (props: Props) => {
             <Close />
           </IconButton>
         )}
-        <Typography variant="h6" style={styles.title}>
-          {props.title}
-        </Typography>
+        <Tooltip title={props.title} placement="bottom" enterDelay={500}>
```
Comment (4ian) [inline newIDE/app/src/UI/DrawerTopBar.js:53]: Let's use 300ms as the delay, as done for the optional tooltip on icon buttons: 
 https://github.com/4ian/GDevelop/blob/2d899d7c52590da0f4ffab392d2f4b9a82e957d7/newIDE/app/src/UI/IconButton.js#L62-L71
 
 If you want to go the extra mile, this constant `tooltipEnterDelay` can be exported in a `UI/Tooltip.js` file to ensure consistency should we tweak this in the future. 

(I'm hesitant to say to abstract the entire material-ui `Tooltip` component in a separate file, because its usage is very much dependent on the context, dependent on material-ui, and because `newIDE/app/src/UI/DrawerTopBar.js` is already in the UI folder, so it has the "right" to use material-ui's Tooltip directly).

File: newIDE/app/src/UI/DrawerTopBar.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ import Toolbar from '@material-ui/core/Toolbar';
 import IconButton from '@material-ui/core/IconButton';
 import Typography from '@material-ui/core/Typography';
 import Close from '@material-ui/icons/Close';
+import { Tooltip } from '@material-ui/core';
```
Comment (4ian) [inline newIDE/app/src/UI/DrawerTopBar.js:8]: I tend to prefer `import Tooltip from '@material-ui/core/Tooltip'` as it helps tree shaking which is not done automatically with this version. See https://v4.mui.com/guides/minimizing-bundle-size/

This being said, we're using so much of `material-ui/core` that I'm not sure it's worth it (it's definitely worth for `@material-ui/icons`), and should probably be linted if we want to enforce ti.

**Review by 4ian — APPROVED** [review]
See two nitpickings, otherwise LGTM! :)

File: newIDE/app/src/UI/DrawerTopBar.js (hunk 1 above)
Comment (AlexandreSi) [reply newIDE/app/src/UI/DrawerTopBar.js:53]: Ok, thanks for this criterium for being in the UI folder or not. For now, I will just define a constant for the delay.

**Comment by AlexandreSi** [comment]
@4ian I added a commit to force update instance list when modifying instances properties (I had troubles reorganizing z orders on my project with a lot of instances).
The last commit is meant to be coherent: unsaved changes were passed down when children in row mode, I don't think they shouldn't be passed if children are in column mode.

File: newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js [hunk 3]
```diff
@@ -70,6 +70,7 @@ const styles = {
     marginTop: 22, //Properly align with the text field
     paddingLeft: 12,
     paddingRight: 12,
+    boxSizing: 'border-box',
```
Comment (4ian) [inline newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js:73]: Good catch!!

File: newIDE/app/src/UI/Tooltip.js [hunk 4]
```diff
@@ -0,0 +1 @@
+export const tooltipEnterDelay = 300;
```
Comment (4ian) [inline newIDE/app/src/UI/Tooltip.js:1]: nit: // @flow ;)

File: newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js [hunk 5]
```diff
@@ -25,6 +25,7 @@ type Props = {|
   layout: gdLayout,
   instances: Array<gdInitialInstance>,
   onEditObjectByName: string => void,
+  onInstancesModified?: Instances => void,
```
Comment (4ian) [inline newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js:28]: Actually, this is a `Array<gdInitialInstance>` that is passed to onInstancesModified - this is more precise than a `Instances`.

`Instances` is a generic type for PropertiesEditor - as PropertiesEditor can be used for anything else that would have "properties".
In theory, we would have typed PropertiesEditor as a generic component in Flow that would take a type `Instances` as parameter (a `PropertiesEditor<Instances>` if you follow me). 
And Flow would have deduced that this `Instances` type is in this case a `Array<gdInitialInstance>`.

In practice it was too hard, so we just typed this as a "Object" type (i.e: a bit like "any"):
image

Let's avoid leaking this to the parent, and use Array<gdInitialInstance>, much like the `instances` prop that is passed down.

**Review by 4ian — APPROVED** [review]

File: newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js (hunk 5 above)
Comment (AlexandreSi) [reply newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js:28]: Ok, thanks for the precision!

**Comment by 4ian** [comment]
Great stuff!
